---
apiVersion: v1
kind: Service
metadata:
  name: ms-nginx
  namespace: dev
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - name: nginx
    port: 80
    targetPort: nginx
    protocol: TCP
  selector:
    app: ms-nginx
