---
apiVersion: v1
kind: Service
metadata:
  name: ms-redis
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    app: ms-redis
