---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-redis
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-redis
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-redis
    spec:
      containers:
        - name: ms-redis
          image: redis:7.0-alpine
          imagePullPolicy: Always
          command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          volumeMounts:
            - name: redis-volume
              mountPath: /usr/local/etc/redis/
      volumes:
        - name: redis-volume
          configMap:
            name: redis-configmap
            items:
              - key: redis.conf
                path: redis.conf
