---
apiVersion: v1
kind: Service
metadata:
  name: ms-users
  namespace: dev
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: ms-users
