---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-users
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ms-users
    spec:
      containers:
      - name: ms-users
        image: edcilo/edc_users:develop
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: FLASK_DEBUG
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: FLASK_DEBUG
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: APP_ENV
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: APP_NAME
        - name: APP_VERSION
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: APP_VERSION
        - name: APP_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ms-secrets
              key: APP_SECRET_KEY
        - name: APP_TIMEZONE
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: APP_TIMEZONE
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: DB_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-secrets
              key: DB_PASSWORD
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: REDIS_PORT
        - name: REDIS_DB
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: REDIS_DB
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ms-secrets
              key: REDIS_PASSWORD
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ms-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: ms-secrets
              key: S3_SECRET_KEY
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: S3_REGION
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: ms-users-configmap
              key: S3_BUCKET
        resources:
          requests:
            cpu: 250m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        livenessProbe:
          httpGet:
            path: /api/v1/users/
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 60
