apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: dev
  name: postgres-pvc
  labels:
    app: postgres
spec:
  resources:
    requests:
      storage: 200Mi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
