apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: postgres-service
  labels:
    app: postgres
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
  - name: postgres
    port: 5432
    targetPort: postgres
    protocol: TCP
