apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15.1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: postgres-configmap
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USER
                  name: postgres-configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          volumeMounts:
            - name: entrypoint-sql
              mountPath: /docker-entrypoint-initdb.d
            # - name: postgresdata
            #   mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: entrypoint-sql
          configMap:
            name: postgres-configmap
            items:
              - key: entrypoint.sql
                path: init.sql
