apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: mysql-service
  labels:
    app: mysql
spec:
  type: LoadBalancer
  selector:
    app: mysql
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
    protocol: TCP
