apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mariadb:10
          imagePullPolicy: IfNotPresent
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
              value: "0"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: mysql-configmap
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: mysql-configmap
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: mysql-configmap
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: mysql-configmap
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 500m
          volumeMounts:
            - name: entrypoint-sql
              mountPath: /docker-entrypoint-initdb.d
          #   - name: 
          #   - name: mysqldata
          #     mountPath: /var/lib/mysql

      volumes:
        - name: mysqldata
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: entrypoint-sql
          configMap:
            name: mysql-configmap
            items:
              - key: entrypoint.sql
                path: init.sql
