# reference  https://www.phillipsj.net/posts/k3s-enable-nfs-storage/
# helm chart https://artifacthub.io/packages/helm/nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
# add this manifest to /var/lib/rancher/k3s/server/manifests in the master node
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nfs
  namespace: default
spec:
  chart: nfs-subdir-external-provisioner
  repo: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
  targetNamespace: default
  set:
    nfs.server: 192.168.1.110
    nfs.path: /opt/nfs/k8s
    storageClass.name: nfs
